// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmjorhzwfkapgjdobkvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhtam9yaHp3ZmthcGdqZG9ia3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NTM1NzksImV4cCI6MjA2MDQyOTU3OX0.2T-cvnv7c1RbyqeNYDGeXJkv6mnEhpk86dI_AgtpfLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);